# -*- coding: utf-8 -*-
"""DSE_6000_Final_Group_Project_EDA+ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-81r9hOLBSMJOUM5eWN-eM-ruS6d004M
"""

from google.colab import files
import pandas as pd
import io
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder

# 1. Load the dataset
uploaded = files.upload()

dataframes = {}

for filename, file in uploaded.items():
    df = pd.read_csv(io.BytesIO(file))
    dataframes[filename] = df
    print(f"Loaded: {filename} ({df.shape[0]} rows, {df.shape[1]} columns)")

df = dataframes['cleaned_data (2).csv']

df.head()

# Compared to other demographics, Employment has the highest average disparity among categories. This is
# followed by Income, Age, and Mental Health.

# Race has the lowest average disparity across demographics.

sd_by_demo = df.groupby('demographic')['disparity_value_num'].mean().sort_values(ascending=False)
sns.set_theme(style="whitegrid", font_scale=1.25)
plt.figure(figsize=(12, 7))
palette = sns.color_palette("magma_r", len(sd_by_demo))

sd_demo_plot = sd_by_demo.plot.bar(color=palette, edgecolor='black', title='Demographics by Average Smoking Disparities')
sd_demo_plot.set_ylabel('Average Smoking Disparity')
sd_demo_plot.set_xlabel('Demographic')

for i, v in enumerate(sd_by_demo):
    sd_demo_plot.text(
        i, v + (0.02 * sd_by_demo.max()),
        f"{v:.2f}",
        ha="center",
        va="bottom",
        fontsize=12,
        fontweight='bold'
    )
plt.xticks(rotation=45, ha='right')
sd_demo_plot.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# Top 10 focus groups with the highest smoking disparity compared to all other groups:

# Employment has the highest average disparity among demographics, in large part, due to
# people unable to work or who are unemployed having the largest disparities across categories.

# Other factors like severe mental health and low socioeconomic status cause higher smoking disparities as well.

sd_by_focus = df.groupby('comparing_focus_group')['disparity_value_num'].mean().sort_values(ascending=False).head(10)

sns.set_theme(style="whitegrid", font_scale=1.25)
plt.figure(figsize=(12, 7))

palette = sns.color_palette("rocket_r", len(sd_by_focus))


sd_focus_plot = sd_by_focus.plot.bar(color=palette, edgecolor='black', title='Top 10 Groups by Average Smoking Disparities')
sd_focus_plot.set_ylabel('Average Smoking Disparity')
sd_focus_plot.set_xlabel('Comparing Focus Group')

for i, v in enumerate(sd_by_focus):
    sd_focus_plot.text(
        i,
        v + (0.02 * sd_by_focus.max()),
        f"{v:.2f}",
        ha="center",
        va="bottom",
        fontsize=12,
        fontweight='bold'
    )

plt.xticks(rotation=45, ha='right')
sd_focus_plot.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# Top 10 focus groups with the lowest smoking disparity compared to all other groups

# People who are retired have the lowest smoking disparity, followed by above average
# income group (+$75K), people aged 65+, and Homemakers/students.

sd_by_focus_low = df.groupby('comparing_focus_group')['disparity_value_num'].mean().sort_values().head(10)

sns.set_theme(style="whitegrid", font_scale=1.25)
plt.figure(figsize=(12, 7))

palette = sns.color_palette("ch:s=.25,rot=-.35", len(sd_by_focus_low))

sd_focus_plot_low = sd_by_focus_low.plot.bar(color=palette, edgecolor='black', title='Bottom 10 Groups by Average Smoking Disparities')
sd_focus_plot_low.set_ylabel('Average Smoking Disparity')
sd_focus_plot_low.set_xlabel('Comparing Focus Group')

for i, v in enumerate(sd_by_focus_low):
    sd_focus_plot_low.text(
        i,
        v + (0.02 * sd_by_focus_low.max()),
        f"{v:.2f}",
        ha="center",
        va="bottom",
        fontsize=12,
        fontweight='bold'
    )
plt.xticks(rotation=45, ha='right')
sd_focus_plot_low.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Correlation Matrix
subset_df = df[['comparing_focus_group', 'to_reference_group',
                'focus_prevalence_num', 'reference_prevalence_num', 'disparity_value_num']]

subset_encoded = pd.get_dummies(subset_df, columns=['comparing_focus_group', 'to_reference_group'], drop_first=True)

new_cols = []
for col in subset_encoded.columns:
    if col.startswith('comparing_focus_group_'):
        new_cols.append('focus_' + col.replace('comparing_focus_group_', ''))
    elif col.startswith('to_reference_group_'):
        new_cols.append('ref_' + col.replace('to_reference_group_', ''))
    else:
        new_cols.append(col)

subset_encoded.columns = new_cols
cor_matrix = subset_encoded.corr()

# Keep only "strong" correlations above threshold
threshold = 0.2
strong_cor = cor_matrix.where(cor_matrix.abs() > threshold)

# Remove columns and rows with all NaN (i.e., no strong correlations)
cols_to_keep = strong_cor.columns[strong_cor.notna().any()]
strong_cor_clean = strong_cor.loc[cols_to_keep, cols_to_keep]

# Split visual in half
mask = np.triu(np.ones_like(cor_matrix, dtype=bool))

strong_cor = cor_matrix[cor_matrix.abs() > 0.2]
plt.figure(figsize=(14, 10))
sns.set(font_scale=1.1)
sns.heatmap(strong_cor_clean, mask=mask, cmap='coolwarm', center=0)
plt.title("Strong Correlation Matrix")
plt.show()



"""
Employment:

  Categories like "Unable to work" and "Retired" in both focus and reference groups have high correlations with each other and with disparity, which supports a previous finding that employment has high influence on disparity with respect to other groups.

Income Groups:

  Categories ref_20K-75K and ref_<20K and ref_<20000 are positively correlated with each other and the disparity value.

  On the other hand, the focus income group focus_>=75K show negative or weak correlation with disparity.

  Lower income groups in the reference population seem to be associated with smaller disparities, as a result of higher smoking rates. In contrast, higher-income focus groups tend to have lower disparities."""



"""Model Build"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
import seaborn as sns

df.describe()

df['comparing_focus_group'].unique()

focus_encoder = OrdinalEncoder()
df['focus_encoded'] = focus_encoder.fit_transform(df[['comparing_focus_group']])

ref_encoder = OrdinalEncoder()
df['ref_encoded'] = ref_encoder.fit_transform(df[['to_reference_group']])

X = df[['focus_prevalence_num', 'reference_prevalence_num', 'focus_encoded',	'ref_encoded']]
y = df['disparity_value_num']
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Linear regression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
linear_pred = linear_model.predict(X_test)

# Random forest
forest = RandomForestRegressor(n_estimators = 200, random_state = 42)
forest.fit(X_train, y_train)
forest_pred = forest.predict(X_test)

# XGBoost model
xgb = XGBRegressor(n_estimators = 200, random_state = 42)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

# Calculate mean squared error for each model
linear_mse = mean_squared_error(y_test, linear_pred)
forest_mse = mean_squared_error(y_test, forest_pred)
xgb_mse = mean_squared_error(y_test, xgb_pred)

# Print the results
print(f"Linear regression MSE: {linear_mse}")
print(f"Random forest MSE: {forest_mse}")
print(f"XGBoost MSE: {xgb_mse}")

"""Model Choice:

Based on the three models tested, we choose Random Forest as our best model because it has the lowest Mean squared error.

Linear regression performs the worst due to the high MSE of 0.2. XGBoost performs much better with a low MSE of 0.0048.

This difference in MSE comparing linear to non-linear models means that there is a non-linear relationship between smoking disparity and the explanatory variables (the focus and reference groups).
"""

y_pred = linear_model.predict(X_train)
residuals = y_train - y_pred
residuals

import matplotlib.pyplot as plt
plt.scatter(y_train, residuals)
plt.xlabel('Actual Disparity')
plt.ylabel('Residuals')
plt.show()

"""Residuals vs. Actuals - Linear Regression

This graph above shows a clear positive relationship between the residuals (difference in training disparity and predicted disparity) and the actual disparity.

So the implication is that the model is underestimating when actual disparity increases, with our residuals being positive for high values. Then, the model is overestimating for low values, with our residuals being low or negative.

The pattern means that linear regression is too biased and cannot capture non-linear relationships well. This is why the non-linear models, Random Forest and XGBoost, perform better than Linear Regression.
"""

